/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorBgBase = "#121214"; // Page background — warm near-black, Figma Dev Handover April 2026
export const ColorBgSurface = "#1c191f"; // Cards, inputs, trending cards
export const ColorBgElevated = "#252530"; // Hover states, tooltips
export const ColorBgSheet = "#1f1f1f"; // Sign Up full-screen bg
export const ColorBgInput = "#1c191f"; // Phone input field
export const ColorTextPrimary = "#ffffff"; // Headlines, tickers, prices
export const ColorTextSecondary = "#a5a0ab"; // Warm gray — inactive tabs, subtitles, View all
export const ColorTextMuted = "#767575"; // Placeholders, OR divider
export const ColorTextSubtitle = "#acabaa"; // Phone auth body copy
export const ColorTextFineprint = "#57505e"; // Terms of service
export const ColorUp = "#00CC88"; // Positive % change, upward sparklines
export const ColorDown = "#FF4D6A"; // Negative % change, downward sparklines
export const ColorCtaPrimary = "#ffffff"; // Primary CTA buttons
export const ColorCtaPrimaryText = "#000000"; // Text on primary CTA
export const ColorCtaGradientEnd = "#d4d4d4"; // Continue button gradient end
export const ColorBorderInput = "#2b282e"; // Input borders, ghost button stroke
export const ColorBorderSubtle = "rgba(255,255,255,0.05)"; // Row dividers
export const ColorGoogleBtnBg = "#121214"; // Continue with Google bg
export const ColorGoogleBtnText = "#e7e7e7"; // Continue with Google text
export const Spacing1 = "4px"; // Base unit
export const Spacing2 = "8px"; // Component gap small (tab row gap, card gap)
export const Spacing3 = "12px"; // Component gap medium (bottom bar gap)
export const Spacing4 = "16px"; // Screen horizontal padding
export const Spacing5 = "20px"; // Section gap
export const Spacing6 = "24px"; // Section gap large
export const SpacingScreenX = "16px"; // Edge to content padding
export const SpacingCardsGap = "16px"; // Trending card gap
export const SpacingSectionY = "20px"; // Gap above section header
export const SpacingStatusBar = "47px"; // iPhone 13/14 notch area
export const SpacingScreenW = "390px"; // iPhone 14/15 frame width
export const SpacingScreenH = "844px"; // iPhone 14/15 frame height
export const RadiusCard = "32px"; // Trending cards, surface cards — squircle-style
export const RadiusTab = "32px"; // Filter tab pills
export const RadiusCta = "48px"; // Continue / Get Stocks CTA pill
export const RadiusInput = "99px"; // Phone input field — full pill
export const RadiusGoogleBtn = "32px"; // Continue with Google button
export const RadiusSearchBtn = "32px"; // Search button in bottom bar
export const RadiusBuysellBtn = "32px"; // Buy/Sell CTA pill
export const RadiusActionBtn = "32px"; // Add Funds / Withdraw ghost buttons
export const RadiusBadge = "999px"; // Change badge pill
export const RadiusAvatar = "50%"; // User avatar circle
export const RadiusCoinIcon = "12px"; // Coin icon in trending card
export const SizeTrendingCardW = "160px"; // Trending card width
export const SizeTrendingCardH = "188px"; // Trending card height
export const SizeBottomBarH = "56px"; // Bottom action bar height
export const SizeBottomBarW = "352px"; // Bottom action bar total width
export const SizeSearchBtnW = "56px"; // Search button width
export const SizeSearchBtnH = "55px"; // Search button height
export const SizeBuysellBtnW = "284px"; // Buy/Sell button width
export const SizeAvatar = "44px"; // Avatar circle diameter
export const SizeActionBtnW = "176px"; // Add Funds / Withdraw width
export const SizeActionBtnH = "48px"; // Add Funds / Withdraw height
export const SizeCtaH = "56px"; // Primary CTA height
export const FontFamilyPrimary = "'Saans', 'Inter', sans-serif"; // Brand font — Saans variable, fallback Inter
export const FontSizeBrandLogo = "24px"; // 'Liquid' wordmark nav
export const FontSizePhoneAuthH1 = "36px"; // Phone auth heading — Enter your phone number
export const FontSizeSectionHeader = "20px"; // Trending Now, Market Assets section labels
export const FontSizeSignupHeadline = "24px"; // 2 Free Tesla Stocks
export const FontSizeTabLabel = "16px"; // Filter tab pills — larger than typical mobile
export const FontSizeBody = "16px"; // Phone auth subtitle, action button labels
export const FontSizeCta = "14px"; // All CTA buttons — Continue, Get Stocks, Buy/Sell
export const FontSizeViewAll = "14px"; // Section View all links
export const FontSizeSignupKicker = "10px"; // GET STARTED WITH LIQUID — uppercase kicker
export const FontSizeSignupSubtitle = "14px"; // Create your account...
export const FontSizeInputPlaceholder = "18px"; // Phone number placeholder
export const FontSizeFineprint = "11px"; // Terms of service fine print
export const FontSizeOrDivider = "18px"; // OR between auth options
export const FontSizeAssetPrice = "14px"; // Asset list price
export const FontSizeAssetName = "12px"; // Asset full name (secondary)
export const FontSizeChangeBadge = "13px"; // % change in trending card
export const FontWeightRegular = "400"; // Saans 380 → CSS 400
export const FontWeightSemibold = "600"; // Saans 570 → CSS 600
export const FontWeightBold = "700"; // Saans 670 → CSS 700
export const FontWeightHeavy = "800"; // Saans 790 → CSS 800 — nav logo, headlines, Market Assets
